- name: 'csp-violation-report-endpoint'
  uriPattern: 'csp-violation-report'
  defaults:
    '@package': 'CodeQ.CspReportEndpoint'
    '@controller': 'Endpoint'
    '@action': 'report'
    '@format': 'html'
  httpMethods: ['POST']
