- name: 'csp-violation-report-endpoint'
  uriPattern: 'csp-violation-report-endpoint'
  default:
    '@package': 'CodeQ.NeosCspReportEndpoint'
    '@controller': 'Endpoint'
    '@action': 'report'
    '@format': 'html'
